--liquibase formatted sql

--changeset mmayakina:1
CREATE TABLE animalsInShelter
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    age int NOT NULL,
    disabilities BOOLEAN NOT NULL
);

