--liquibase formatted sql

--changeset mmayakina:1
CREATE TABLE animals_in_shelter
(
    idAnimal     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nameAnimal   TEXT    NOT NULL,
    age          int     NOT NULL,
    disabilities BOOLEAN NOT NULL
);

--changeset mmayakina:2
CREATE TABLE users
(
    idUser     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstName  TEXT NOT NULL,
    lastName   TEXT NOT NULL,
    numberUser int  NOT NULL
        chatId int NOT NULL
);

--changeset mmayakina:3
CREATE TABLE animals_in_house
(
    adoption                INT PRIMARY KEY,
    idAnimal                INT  NOT NULL,
    idUser                  INT  NOT NULL,
    lastDateProbationPeriod DATE NOT NULL,
    lastFoto                TEXT,
    lastTextReport          TEXT,
    lastReportDate          DATE
);

CREATE TABLE report
(
    idReport         INT PRIMARY KEY,
    ration           TEXT,
    GeneralWellBeing TEXT,
    animalBehavior   TEXT,
    lastTextReport   TEXT,
--  data
--  extension
--     lastDateProbationPeriod DATE NOT NULL,
--     lastReportDate          DATE
);

-- --changeset sergeyPanin:3
-- ALTER TABLE animalsInHouse
--     ADD COLUMN adoption LONG INT PRIMARY KEY;





